### ISSUE TITLE
clarify format of the "content" inside a message

### ISSUE THREAD

**Issue by soapdog** [ssb-ngi-pointer/bendy-butt-spec#12]
Bendy butt spec specifies `content` as:

> content an array of a dictionary encoding the data relevant to the meta feed and a signature. The signature is the concatenation of the string 'metafeeds' encoded as bytes and the bytes of the content payload, signed using the private key of the sub feed. If content is encrypted this will also be encrypted as a binary SSB-BFE encoded box2 message

Content is written as Bencoded list of dictionaries but, the example on the page makes it look like a JS object. This can lead to the misunderstanding that the content is JSON inside a Bencoded message. It might be beneficial to add a word or two clarifying that that is not the case.

**Comment by staltz** [comment]
I believe the changes I just made helped address this! Let me know
