### ISSUE TITLE
first review comments

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/bendy-butt-spec#2]
1. define sequence as varint (the one we already use in bipf, i'd say)
1. define that previous for seq:0 is an _empty message tfk_ (so zero bytes instead of nothing)
1. i'd move timestamp inside  message content, if possible
1. content is encoded as bipf, too, i guess?
1. signature and content signature? why?

**Comment by arj03** [comment]
This is great feedback!

>     1. define sequence as varint (the one we already use in bipf, i'd say)

I was referrering to this:

INT     : 2  // little endian 32 bit integer

I'll make that a bit clearer

>     2. define that previous for seq:0 is an _empty message tfk_ (so zero bytes instead of nothing)

Good idea, thanks!
 
>     3. i'd move timestamp inside  message content, if possible

I'd rather leave it here to make it easier for clients as that matches closer with classic SSB format.
 
>     4. content is encoded as bipf, too, i guess?

Yes, clarified that a bit

>     5. signature and content signature? why?

That was not very clear maybe. 1 signature for sub feed and 1 signature for meta feed. I have defined what fields MUST be in content, that should maybe make things a bit clearer I hope :)

**Comment by cryptix** [comment]
:+1: 

Resolved after our call and the recent commits. :)
