### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/bendy-butt-spec#4]
Now that we moved away from bipf as the encoding, this needs a new name. `bipfy badger` will be way to confusing if it's not using bipf.

Personally, I like _boring butt_. It also abbreviates nicely to bb. It follows the lineage of _boring ssb_ (using existing tech).

**Comment by arj03** [comment]
How do we move forward with this? :) There were some suggested names on SSB.

**Comment by cryptix** [comment]
Right..! I probably should have put a deadline on the voting process. Here are the results so far:

* Muesli: 10 votes
* bendy-butt / ssbendy: 9 votes
* buttform: 4 votes
* ssb-metafeed-00: 3 votes
* peach256/peachTree: 3 vots
* ButtFor: 2 votes
* buttshape: 1 vote

**Comment by cryptix** [comment]
no matter which we pick i'm still strongly suggesting we put a version marker on the string suffixes (i.e. `@foo.muesli-v1` or `...bendybutt-v1`).

**Comment by arj03** [comment]
Yep. I like bendy butt because it shortens to bbfeed/bbmsg which can be read as boring butt :) But muesli also works. Just seems a bit more verbose.

**Comment by cblgh** [comment]
so far i liked meta muesli the best :) implies many different varieties & is a meaningful alliteration

**Comment by staltz** [comment]
I vote for bendy-butt

**Comment by mycognosist** [comment]
Feels a bit like naming a band ;) Hmm...tough call but I think I also like muesli / meta muesli the most. It's fun, reflects the heterogeneity of the thing being named and it's about breakfast.

In terms of grokkability-at-a-glance, I reckon bendy-butt is best. It's the closest to being a direct description of what the thing is.

P.s. we might need a tie-breaker from Zelf :)
